version: '3.7'
services:
  netdata:
    image: netdata/netdata
    hostname: www.reisslein-analytik.de # set to fqdn of host
    #    ports:
    #      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./netdata.conf:/etc/netdata/netdata.conf
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/os-release:/host/etc/os-release:ro 
    networks:
      - proxy
    restart: unless-stopped
    container_name: netdata
    environment:
      - PGID=114 #grep docker /etc/group | cut -d ':' -f 3
    labels:
      - traefik.enable=true
      - traefik.docker.network=${DOCKER_NETWORK_NAME}
      - traefik.http.services.netdata.loadbalancer.server.port=19999
      - traefik.http.services.netdata.loadbalancer.server.scheme=http
      - traefik.http.routers.netdata.rule=Host(`netdata.reisslein-analytik.de`)
      - traefik.http.routers.netdata.entrypoints=http
        #- traefik.http.routers.netdata.middlewares=redirect@file
      - traefik.http.routers.netdata-https.rule=Host(`netdata.reisslein-analytik.de`)
      - traefik.http.routers.netdata-https.entrypoints=https
      - traefik.http.routers.netdata-https.tls=true
      - traefik.http.routers.netdata-https.tls.certResolver=default
      - traefik.http.routers.netdata-https.middlewares=auth@file        
networks:
  proxy:
    external:
      name: ${DOCKER_NETWORK_NAME}        
